---
version: 1
environment: local
health_check:
  enabled: false
  port: 1234
  interface: 0.0.0.0
  debug_envs:
    - local
jaeger_config:
  service_name: template-service-name
  logging: true
  enabled: false
  trace_id_header: template-app-trace-id
  sampler:
    type: const
    param: true
monitoring:
  enabled: false
masking_fields:
  - token
  - access_token
  - refresh_token
  - epkId
  - profileId
user_save_collisions_tries: 2
self_service_with_state_save_messages: true